language: r

sudo: required

env: _R_CHECK_CRAN_INCOMING_=FALSE

r_packages:
  - covr
  - devtools
  - BiasedUrn
  - metafor
  - digest

r_github_packages:
  - codecov/example-r

after_success:
  - Rscript -e 'library(covr);codecov()'